### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by SealinGp** [ueaner/soap#1]
Fatal error:  Uncaught SoapFault exception: [HTTP] Not Found in /root/Apache/www/soap-master/test.php:22
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://localhos...', 'urn:ABOUTC_Pers...', 2, 0)
#1 /root/Apache/www/soap-master/test.php(22): SoapClient->__soapCall('say', Array)
#2 {main}
  thrown in /root/Apache/www/soap-master/test.php on line 22
-----------------------------------------------------------------------------------
I entirely do written in the rename and do nothing ,(php-soap has installed) and then access the test.php,
recently learning the soap~hope you can help me with that~

**Comment by ueaner** [comment]
Fixed, try **git pull**, please.

**Comment by SealinGp** [comment]
OK

**Comment by ueaner** [comment]
@SealinGp Has the problem been solved?

**Comment by SealinGp** [comment]
Hi,you seems to update the wrong file, there is no wsdl file in dir wsdl ,so It can't parse wsdl file

**Comment by SealinGp** [comment]
The recent days I've figured it out by google,and write an test myself.but thanks anyway

**Comment by ueaner** [comment]
@SealinGp my bad, missing xml dir. thank you for your reply.
